Hosts:
  - id: Host-1
    cpu: 3500000000
    mem: 16777216
    net: 10000
    transmissionDelay: 10
    ip: 0.0.0.0

Tasks:
  - id: 1
    type: normal_image_processing
    arriveTime: 0
    value: 1
    sensitive: true
    isSoftDeadline: true
  - id: 2
    type: normal_image_processing
    arriveTime: 0
    value: 1
    sensitive: true
    isSoftDeadline: true
  - id: 3
    type: normal_image_processing
    arriveTime: 0
    value: 1
    sensitive: true
    isSoftDeadline: true
  - id: 4
    type: normal_image_processing
    arriveTime: 0
    value: 1
    sensitive: true
    isSoftDeadline: true
